CREATE TABLE `boldbin` (
bin_uri varchar(255) NOT NULL PRIMARY KEY,
phylum_taxID INT(11),
phylum_name VARCHAR(255),
class_taxID INT(11),	
class_name varchar(255) DEFAULT NULL,	
order_taxID INT(11),	
order_name varchar(255) DEFAULT NULL, 
family_taxID INT(11),	
family_name varchar(255) DEFAULT NULL,	
subfamily_taxID INT(11),
subfamily_name varchar(255) DEFAULT NULL,
genus_taxID INT(11),
genus_name varchar(255) DEFAULT NULL,
species_taxID INT(11),
species_name varchar(255) DEFAULT NULL,
subspecies_taxID INT(11),
subspecies_name varchar(255) DEFAULT NULL,
identification_provided_by varchar(255) DEFAULT NULL,
identification_method varchar(255) DEFAULT NULL,
identification_reference varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET= UTF8;


CREATE TABLE `boldtsvtaxa` (
processid varchar(255) NOT NULL,
bin_uri varchar(255),
phylum_taxID INT(11),
phylum_name VARCHAR(255),
class_taxID INT(11),	
class_name varchar(255) DEFAULT NULL,	
order_taxID INT(11),	
order_name varchar(255) DEFAULT NULL, 
family_taxID INT(11),	
family_name varchar(255) DEFAULT NULL,	
subfamily_taxID INT(11),
subfamily_name varchar(255) DEFAULT NULL,
genus_taxID INT(11),
genus_name varchar(255) DEFAULT NULL,
species_taxID INT(11),
species_name varchar(255) DEFAULT NULL,
subspecies_taxID INT(11),
subspecies_name varchar(255) DEFAULT NULL,
identification_provided_by varchar(255) DEFAULT NULL,
identification_method varchar(255) DEFAULT NULL,
identification_reference varchar(255) DEFAULT NULL,
classification varchar(255)
) ENGINE=InnoDB DEFAULT CHARSET= UTF8;

CREATE TABLE `boldtaxonomy` (
processid varchar(255) NOT NULL,
bin_uri varchar(255) PRIMARY KEY NOT NULL,
phylum_taxID INT(11),
phylum_name VARCHAR(255),
class_taxID INT(11),	
class_name varchar(255) DEFAULT NULL,	
order_taxID INT(11),	
order_name varchar(255) DEFAULT NULL, 
family_taxID INT(11),	
family_name varchar(255) DEFAULT NULL,	
genus_taxID INT(11),
genus_name varchar(255) DEFAULT NULL,
species_taxID INT(11),
species_name varchar(255) DEFAULT NULL,
identification_provided_by varchar(255) DEFAULT NULL,
identification_method varchar(255) DEFAULT NULL,
identification_reference varchar(255) DEFAULT NULL,
classification varchar(255),
supportingNameUsages INT(11)
) ENGINE=InnoDB DEFAULT CHARSET= UTF8;

create table bins (
bin_uri varchar(255) PRIMARY KEY NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET= UTF8;

CREATE TABLE `boldconsensus` (
bin_uri varchar(255) PRIMARY KEY NOT NULL,
phylum_taxID INT(11),
phylum_sup_usages INT(11),
phylum_num_usages INT(11),
phylum_name VARCHAR(255),
class_taxID INT(11),	
class_sup_usages INT(11),
class_num_usages INT(11),	
class_name varchar(255) DEFAULT NULL,	
order_taxID INT(11),	
order_sup_usages INT(11),	
order_num_usages INT(11),	
order_name varchar(255) DEFAULT NULL, 
family_taxID INT(11),	
family_sup_usages INT(11),
family_num_usages INT(11),
family_name varchar(255) DEFAULT NULL,	
genus_taxID INT(11),
genus_sup_usages INT(11),
genus_num_usages INT(11),
genus_name varchar(255) DEFAULT NULL,
species_taxID INT(11),
species_sup_usages INT(11),
species_num_usages INT(11),
species_name varchar(255) DEFAULT NULL,
index(phylum_taxID),
index(phylum_sup_usages),
index(phylum_num_usages),
index(class_taxID),
index(class_sup_usages),
index(class_num_usages),
index(order_taxID),
index(order_sup_usages),
index(order_num_usages),
index(family_taxID),
index(family_sup_usages),
index(family_num_usages),
index(genus_taxID),
index(genus_sup_usages),
index(genus_num_usages),
index(species_taxID),
index(species_sup_usages),
index(species_num_usages)

) ENGINE=InnoDB DEFAULT CHARSET= UTF8;